sudo: required
services: 
  - docker

before_install:
  - docker build -t maazmalik/multi-react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true maazmalik/multi-react-test npm test

after_success:
  - docker build -t maazmalik/multi-client ./client
  - docker build -t maazmalik/multi-nginx ./nginx
  - docker build -t maazmalik/multi-server ./server
  - docker build -t maazmalik/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push maazmalik/multi-client
  - docker push maazmalik/multi-nginx
  - docker push maazmalik/multi-server
  - docker push maazmalik/multi-worker

deploy:
  - provider: elasticbeanstalk
  - region: us-east-2
  - app: Docker-multicontainer  
  - env: DockerMulticontainer-env
  - bucket_name: elasticbeanstalk-us-east-2-265430714165
  - bucket_path: docker_multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
