sudo: required
services: 
  - docker

before_install:
  - docker build -t maaz/multi-react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true maaz/multi-react-test npm test

after_success:
  - docker build -t maaz/multi-client ./client
  - docker build -t maaz/multi-nginx ./nginx
  - docker build -t maaz/multi-server ./server
  - docker build -t maaz/multi -worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push maaz/multi-client
  - docker push maaz/multi-nginx
  - docker push maaz/multi-server
  - docker push maaz/multi-worker

    
